### ISSUE TITLE
Translations Support

### ISSUE THREAD

**Issue by hernandev** [laravelio/portal#109]
Hi, i'm from Brazilian Laravel Community and we're going to deploy this code on a Portuguese flavored version (already live on: http://duvidas.laravel.com.br ).

Replacing the hardcoded string to a localization with laravel will make our lifes much easyer, the way things are now, it will be a nightmare to merge with upstream and send you back the pull requests.

Once aproved, i can make this

**Comment by driesvints** [comment]
With the upcoming GDPR law we should be required to also provide a privacy policy and terms & conditions in each language we offer. We recently started using Iubenda to help with the privacy part but it would require us to buy a license in each language we offer. We also would have to translate our entire terms and conditions. I currently have no interest in either paying or putting the time into these things so for the current time being, English will be the only available language on the portal. This might change in the future but no guarantees.

**Comment by hernandev** [comment]
@driesvints through https://utopian.io contributors who translate get paid for it.

Maybe a viable option to keep the translations

**Comment by driesvints** [comment]
@hernandev no, the thing is we can't provide translations because we'd have to offer privacy policies for each language which requires us to buy a license for each at Iubenda.
