### ISSUE TITLE
Update to use Gulp build tool

### ISSUE THREAD

**Issue by mattstauffer** [laravelio/portal#153]
Wrap compass with Gulp, and also add javascript concatenation and minification.

**Comment by Tjoosten** [comment]
@driesvints if you want i can make a PR for this.

**Comment by driesvints** [comment]
@Tjoosten I'll be migrating everything to 5.1 within the week so no yet. I actually want to migrate to Elixir soon.

If you want to give it a shot after that that'd be awesome but I'm probably gonna step up development soon and I need to get the frontend development workflow on point soon.

**Comment by Tjoosten** [comment]
@driesvints o ok i will wait then. Is there anything else that i can do?

**Comment by driesvints** [comment]
@Tjoosten at this point very little. In a few weeks I'm gonna need a lot of help. It's just these first steps I have to do myself :)
