### ISSUE TITLE
php artisan migrate --seed --env=local

### ISSUE THREAD

**Issue by fjzwn1992** [laravelio/portal#236]
Hello! I am a newer of laravel！ When I run php artisan migrate --seed --env=local being given as follows.
`  [Illuminate\Database\QueryException]                                                                                                                                                  
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" (SQL: select count(*) as aggregate from "users" where "email" = account@account.com and  
   "id" <> )                                                                                                                                                                            
`
`SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "id"  `.

I'm sorry my English is not particularly good

**Comment by driesvints** [comment]
Hey @fjzwn1992 I'm not particularly sure how this error was triggered. Are you using MySQL as a database?

Since we're very close to releasing the next version of the portal (< 2 months) I'm going to close this as it will be invalid for the new version.
