### ISSUE TITLE
Images come outside the thread/reply borders

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#242]
Example: https://laravel.io/forum/gameq-v3-integration-to-laravel-54

Probably just needs a max-width for images.

![screen shot 2017-06-19 at 2 45 36 pm](https://user-images.githubusercontent.com/594614/27285787-15753482-54fe-11e7-9833-2bb008e55314.png)

**Comment by petarblazevski** [comment]
Is it possible to add a class to every image, automatically? Since you are using Twitter Bootstrap, there is a class called `.img-responsive`. This will fix the issue

**Comment by driesvints** [comment]
Unfortunately no because the content is being generated from the markdown source. I think just a CSS reference to target every `img` element with `max-width: 100%;` will do the trick.
