### ISSUE TITLE
Show poster at top of the message, not at the bottom

### ISSUE THREAD

**Issue by mfn** [laravelio/portal#246]
I find this pretty irritating. To me, the author (incl. the date, etc.) is the foremost important information when digesting some information and it's no different on a forum.

Currently it looks like this:
![image](https://user-images.githubusercontent.com/87493/27289956-04fba0d8-550c-11e7-959f-13a3ee526896.png)

I really think this information belongs at the top. This makes "recognizing" comments in a thread also much better when there's a clear "heading" where currently is none (except the bordered line, of course).

I would also suggest to change the order of information presented here:

1. author
2. when
3. tags

E.g. "UserName replied n minutes ago"

**Comment by fetzi** [comment]
@driesvints reordering the information as suggested makes absolutely sense for me. 

Moving the information to the top looks a little bit strange for me. But I agree that it would be easier if the user information would be on top. Maybe we can relayout to display the users avatar, the username and the time info on the left followed by the tags on the right side.

What do you think?

**Comment by driesvints** [comment]
I completely agree with you both! It would indeed make it easier to distinguish a thread from replies. Feel free to try out something and send in a PR so we can discuss further there :)

**Comment by driesvints** [comment]
Fixed with #250
