### ISSUE TITLE
Cannot post anything to the forum - marked as containing spam

### ISSUE THREAD

**Issue by snapey** [laravelio/portal#253]
Ironically, I was trying to ask how to deal with spam, but my post was marked as spam and could then not post anything - new thread or reply.

![its-spam](https://user-images.githubusercontent.com/328747/27471716-a18940b8-57f0-11e7-8e7b-785fa16edf76.png)

![does not seem to be based on content](https://user-images.githubusercontent.com/328747/27471723-a64e2cda-57f0-11e7-853e-7c2d222a5da8.png)

![cannot post anything](https://user-images.githubusercontent.com/328747/27471732-ae735502-57f0-11e7-8c13-ef16e96fe691.png)

**Comment by driesvints** [comment]
I'm really sorry but I haven't had time yet to look at this. I'll try to see if I can find some time this week.

**Comment by driesvints** [comment]
@snapey heya, I just tried it myself. I can't see any reason why your content would be flagged as spam. Are you still experiencing the problem?

**Comment by snapey** [comment]
Yes, just tried it and still being flagged as spam

![cannot post](https://user-images.githubusercontent.com/328747/28238943-42a5b16c-6957-11e7-8034-76f2d91d8f16.png)

**Comment by driesvints** [comment]
The only way your post can be marked as spam is because of Akismet because that's the only spam method implemented atm. I'm gonna turn it off for now because it has been proven ineffective a lot in the past. But if the forum gets flooded with spam I'll turn it back on and we'll have to look for a different solution.

**Comment by snapey** [comment]
There needs to be a mechanism to report spam so that a mod can check and nuke.  You may need additional moderators to do this though.  The site already has spam items and it was trying to alert this when I first had an issue

**Comment by snapey** [comment]
Still the same.. Did you turn it off?

**Comment by driesvints** [comment]
I forgot we have config caching enabled. I just triggered a new deploy. Can you try again? Sorry about that.

And yeah, I fully agree with you. I'll try to look into improving that and provide more options for users to flag content as spam.

**Comment by snapey** [comment]
I can post now thanks. https://laravel.io/forum/massassignmentexception-in-modelphp-line-444-token

**Comment by driesvints** [comment]
Ok glad it works for you now. Thanks for reporting!
