### ISSUE TITLE
Latest threads on user profiles is in wrong sequence

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#256]
Starts ordering from oldest to newest but should be the other way around.

**Comment by rtamizh** [comment]
User.php(line - 157):

`return $this->threadsRelation->take($amount);`

need to be changed as 

`$this->threadsRelation()->orderBy('created_at', 'desc')->take($amount);`

**Comment by driesvints** [comment]
@rtamizh can you send in a PR? Also you can replace `orderBy(...)` with `latest()` I believe.
