### ISSUE TITLE
Add syntax highlighting 

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#260]
It would be great to have syntax highlighting for the code blocks on the forum. I tried implementing Prism which seems the goto solution but didn't manage to get it working.

http://prismjs.com/

I really like Solarized Dark but maybe the default theme will suffice.

**Comment by introwit** [comment]
@driesvints Already built-in Markdown works great, any specific reason you want to use prismjs?

![md-lio](https://user-images.githubusercontent.com/11228182/27960022-579e7b14-6347-11e7-8d1f-27665da1556c.png)

**Comment by driesvints** [comment]
@introwit how did you get this to work?

**Comment by introwit** [comment]
@driesvints use the language name after the opening backticks and it will do the rest. Example: ```php , ```html , ```json , etc.

```php
<?php

class Action {

}
```

The above was written as (screenshot before posting this)

![md-example](https://user-images.githubusercontent.com/11228182/27960472-0aaf7e1e-6349-11e7-9dcd-53c0d754d924.png)

**Comment by driesvints** [comment]
Hmm, that doesn't seems to work on production. Notice my comment here: https://laravel.io/forum/validate-two-fields-with-the-same-validation-rule

It has the php flag after the code block but it doesn't gets highlighted.

**Comment by introwit** [comment]
@driesvints Seems like I was working on this issue specific branch a few days ago and had included prism css & js in the base layout that day. Just checked out on that branch and started testing the current behavior and I got the highlighting. Completely forgot my past work. But I just included the 2 files and it seems prism detects the language same as MD.

**Comment by driesvints** [comment]
Yeah, I just couldn't get it to work. Feel free to send in a PR.
