### ISSUE TITLE
Add better fallback avatar

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#264]
The current default Gravatar looks a bit out of place. 

This might be replaced with an grayed-out version of a potential future logo.

**Comment by har256b** [comment]
would it be nice to have initials as fallback gravatar?
i.e. the **first letter** from first name or **first letters** of full name
<img width="370" alt="screen shot 2017-07-10 at 01 41 22" src="https://user-images.githubusercontent.com/747479/27998518-15cbf33a-6511-11e7-85e6-80bf76a7aad5.png">

**Comment by driesvints** [comment]
Ow yes that looks really nice! Not sure to pick one or two letters. Two might be best to provide more "uniqueness"?
