### ISSUE TITLE
Subscribe to threads

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#270]
As a user
I want to subscribe to a thread
So that I can receive notifications for new replies

**Story 1: Receive notifications**
Given the user is subscribed to a thread
When the thread receives a new reply
Then the user receives a notification for the reply

**Story 2: Automatically subscribe to a thread after creating it**
Given the user is logged in
When the user creates a new thread
Then the user is subscribed to the thread

**Story 3: Automatically subscribe to a thread after posting a reply**
Given the user is on a thread detail page
When the user replies to the thread
Then the user is subscribed to the thread

**Story 4: Manually subscribe to a thread**
Given the user is on a thread detail page
And the user is not subscribed to a thread yet
When the user clicks the subscribe button
Then the user is subscribed to the thread

**Story 5: Unsubscribe from a thread**
Given the user is on a thread detail page
And the user is subscribed to a thread
When the user clicks the unsubscribe button
Then the user is no longer subscribed to the thread

**Story 6: Unsubscribe from within the email**
Given the user receives a new notification
When the user clicks on the unsubscribe link
Then the user is no longer subscribed to the thread

**Comment by papajmac** [comment]
Change the word "Scenario" to "Story" and you'll make the Agile gods will smile upon you.

**Comment by driesvints** [comment]
@papajmac much better :)

**Comment by driesvints** [comment]
This is now live as of a couple of months already.
