### ISSUE TITLE
Incorrect GitHub profile link is being generated

### ISSUE THREAD

**Issue by introwit** [laravelio/portal#274]
- Thank you for all your work on laravel.io
- The GitHub profile generated on my [laravel.io profile](https://laravel.io/user/introwit) page is incorrect as it contains my 2 year old username resulting in a 404 response. 
- I did test that is the GitHub API returning old/cached data but that's not the case as it returns the correct value for the "login" key in their response.

**Comment by driesvints** [comment]
Ah yeah, I think we just need a way for users to update their Github username. I'll create an issue for it.

**Comment by driesvints** [comment]
I made an issue for this: #275. I think it might be better if the system automatically updated your username instead of you manually having to edit it through a setting.
