### ISSUE TITLE
Set max length for thread titles

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#282]
Not sure how long we should set it.

**Comment by krisnaw** [comment]
How about 50-60 characters? to make it SEO friendly.

**Comment by driesvints** [comment]
@krisnaw yeah that might be a good start.

**Comment by bobbybouwmann** [comment]
Snapchat and eBay for example have a limit of 80 characters. The ideal HTML title tag is limited to 55 characters.


Let's say we set the limit on 60 characters titles like this will pass:
- JSON not possible with MSSQL running on Windows platform? (57)
- How to refresh number of comments on post automatically? (56)
- Call to a member function getClientOriginalName() on null (57)

Also note that titles like this won't pass (they do fit on a desktop screen right now)
- How to create a form with optional fields and generate SQL Query based on Inputs provided? (90)
- belonsToMany returns empty when eager loading and using leftjoin in Eloquent query (82)

I want to PR this, but I just want to be sure that we are all on the same line here. A title should still give enough context for the question. But of course it shouldn't be used for a complete question, only for context.

Let me know what I can do ;)

**Comment by bobbybouwmann** [comment]
My hands were itching so I already created a PR! We can always adjust the size of course ;)
