### ISSUE TITLE
Change password for users connected with Github

### ISSUE THREAD

**Issue by eduardostuart** [laravelio/portal#287]
When I connect with my Github account, I can't set a password because the "current password" is always required.

Two suggestions for this:

Force user to set a password on account creation 

or

Change `UpdatePasswordRequest` and `password.blade` file. Check if the user has GitHub id defined and an empty password.  In other words, make the validation request dynamic. Only show `current password` field if the user has a password defined.

**Comment by driesvints** [comment]
I think an even easier way is to just add a link to the password settings screen to the password reset form. What do you think?

**Comment by eduardostuart** [comment]
@driesvints yes, that's possible too. 
But I'm not sure about user experience here - is a good idea to redirect to another page just to reset the password? ("I'm already on password page"). I prefer option 2 - seems easier to the final user.

**Comment by driesvints** [comment]
You're right. But I wouldn't take Github authentication into account. Just check if the user already has a password or not.

**Comment by driesvints** [comment]
Just pushed this feature on master.
