### ISSUE TITLE
Font size and line height for better readability.

### ISSUE THREAD

**Issue by keevitaja** [laravelio/portal#296]
Hello!

Would you consider setting  content `font-size: 17px` and `line-height: 1.625px` for better readability?

With current settings:
![screenshot_2017-08-03_13-51-12](https://user-images.githubusercontent.com/158787/28918671-f1503aac-7852-11e7-9b5c-857f14e468fe.png)

And with new settings:
![screenshot_2017-08-03_13-50-47](https://user-images.githubusercontent.com/158787/28918676-f9c11dbe-7852-11e7-9449-3791a0835b2b.png)

I know it might be subjective, but imho the last one is so much better.

**Comment by driesvints** [comment]
Heya, yes that's a good idea. You can send in a PR for that if you want. Try to only increase the font-size for the thread content with a specific class.

**Comment by keevitaja** [comment]
Will do!
