### ISSUE TITLE
Delete modal has incorrect text alignment

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#300]
Due to https://github.com/laravelio/portal/pull/298

Needs to be the standard behavior

![screen shot 2017-08-15 at 2 02 13 pm](https://user-images.githubusercontent.com/594614/29315271-953b21f4-81c2-11e7-9b61-155bcf7cc5e4.png)

**Comment by krisnaw** [comment]
Hi @driesvints can I take this bugs?

I've tried by adding this style to ..thread-info-tags class and its work on Chrome and Safari
`           
 .modal-content {
text-align: left;
    }
`

**Comment by driesvints** [comment]
@krisnaw sure. I do think we need to tweak the styles for the `.thread-info-tags` and preventing the modal styles from being adjusted. Without changing anything to `.modal-content` that is. It's a slippery slope to cascading styles from there. I'd rather just fix the original problem than fix the consequences over and over.
