### ISSUE TITLE
Text doesn't breaks in thread box

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#301]
https://laravel.io/forum/laravel-how-to-store-payment-gateway-response-url-data-value-in-database

![screen shot 2017-08-15 at 2 04 54 pm](https://user-images.githubusercontent.com/594614/29315300-c0f2ac68-81c2-11e7-950f-8424934b3013.png)

**Comment by krisnaw** [comment]
Hi @driesvints can I take this bugs?

**Comment by driesvints** [comment]
@krisnaw sure, send in a pr!
