### ISSUE TITLE
How to use roles and manage grant permissions?

### ISSUE THREAD

**Issue by inesarmadabras** [laravelio/portal#308]
Hi,

I'm stuck on making a registered user admin/moderator in the laravel.io new version.

How to make any user as admin of the forum?

Also, I'll give a suggestion: by default, the first user created should be admin.

Thanks,

**Comment by driesvints** [comment]
Heya @inesarmadabras! 

You can use the `type` column on the user. Set this to either 2 (moderator) or 3 (admin). You find a references of the types as constants on the User model. 

There isn't any UI atm to make users admins or moderators but that's something we can add later. 

I agree that we could add a seeded user who is an admin. I'll try to look into this in the near future.
