### ISSUE TITLE
PARSE ERROR 

### ISSUE THREAD

**Issue by chisumo2016** [laravelio/portal#313]
I have cloned your portal project and run composer update .But it appear there's some parse error as shown on screenshot.Kindly assist

bundalla@bundalla-PC MINGW64 /c/laragon/www/portal (master)
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Parse error: syntax error, unexpected '?'

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

bundalla@bundalla-PC MINGW64 /c/laragon/www/portal (master)

**Comment by devcircus** [comment]
are you using php 7.1? That looks like a nullable return type that is only valid in PHP >= 7.1

**Comment by chisumo2016** [comment]
Hi 

Yes i used PHP > = 7.1

**Comment by driesvints** [comment]
I'm not really sure what's going on. I can install the app just fine here. Did you follow the install instructions from the readme? Are you sure you didn't change anything to the code before running the install steps?

**Comment by driesvints** [comment]
I also see you're trying to do a `composer update`. Why are you trying to do that?

**Comment by driesvints** [comment]
I'm going to close this one. Let me know if you need any more help.
