### ISSUE TITLE
The subject field cannot contain an url

### ISSUE THREAD

**Issue by keevitaja** [laravelio/portal#318]
Hello!

After i tried to save a new thread i for error for subject field:

`The subject field cannot contain an url.` 

Of course there is no url in that subject:

`JSON  not possible with MSSQL running on Windows platform?`

![screenshot_2017-10-18_19-52-39](https://user-images.githubusercontent.com/158787/31731563-20545776-b43e-11e7-8531-4671b02eb531.png)

And this is the body with architecture tag

```
Hello!

One of our clients is using a SaaS app which apparently uses Windows MS SQL running on Windows platform. They (saas) do not have prebuilt API for their clients, but they can do a custom "XML" one for each client. Funny, eh?

So i sent them a question today, asking if they could provide me JSON API endpoints instead of XML. They replied NO WAY but explained:

`We're using MS platform. XML is native datatype for MS SQL and SQLXML mapper is native system component. For JSON we do not have a single tool!`

So my question is, can this be true? For me it sounds crazy... but my Windows skills are below zero!
```

**Comment by driesvints** [comment]
That's very odd. I'll take a look at it. Will get back to you.

**Comment by driesvints** [comment]
Heya. I cannot reproduce this. I can create a thread with this content just fine. Can you try again?

**Comment by keevitaja** [comment]
Man, this is just crazy. I copied the subject and body from this bug report and it saved without any hassle.

https://laravel.io/forum/json-not-possible-with-mssql-running-on-windows-platform

PS! I am not shitting you.

**Comment by driesvints** [comment]
> PS! I am not shitting you.

Haha, no worries. Glad you could post it :)
