### ISSUE TITLE
SQL error on Forum page only

### ISSUE THREAD

**Issue by vitorspencer** [laravelio/portal#319]
I have setup the repo in my local environment (mac os, valet, MariaDB).

Everything but the Forum page seems to work fine. I am able to access user's summary pages and posts, etc. However, in the Forum page `/forum` I get the following sql error:

```
SQLSTATE[42000]: Syntax error or access violation: 1055 'portallaravelio.threads.author_id' isn't in GROUP BY (SQL: select `threads`.*, \n
                CASE WHEN COALESCE(MAX(replies.created_at), 0) > threads.created_at\n
                THEN COALESCE(MAX(replies.created_at), 0)\n
                ELSE threads.created_at\n
                END AS latest_creation\n
             from `threads` left join `replies` on `threads`.`id` = `replies`.`replyable_id` and `replies`.`replyable_type` = threads group by `threads`.`id` order by `latest_creation` desc limit 20 offset 0)
```

Anyone experienced this?

**Comment by driesvints** [comment]
Laravel.io makes use of MySQL 5.7 for its DB. Please follow the install instructions from the readme and use Homestead to run the application. If you still run into the same problems after that, feel free to open another issue.
