### ISSUE TITLE
Unable to change username or name in the account

### ISSUE THREAD

**Issue by FreddyCrugger** [laravelio/portal#327]
Unable to change username or name in the account.

I am getting a "Something went wrong
We've been notified and will try to fix the problem as soon as possible. Please open a Github issue if the problem persists.".

Thanks

**Comment by driesvints** [comment]
Heya, thanks for reporting! I'll try to look at it soon.

**Comment by driesvints** [comment]
Hey, sorry this took so long. I don't immediately see what might be going wrong. What's your username and to what new username are you trying to change it?

**Comment by driesvints** [comment]
Gonna close this one. Let me know if the problem persists.
