### ISSUE TITLE
Users should be able to "Like" other users answers

### ISSUE THREAD

**Issue by latr88** [laravelio/portal#334]
After reading somebody's else answer you might want to just give a "thumbs up" to it as you also think it is the right one, it may be helpful for the author to accept or trust it is the right answer to try.

**Comment by driesvints** [comment]
Definitely something to consider. Thanks for suggesting!

**Comment by BobbyBorisov** [comment]
Anybody working on this? I would like to get this one!

**Comment by driesvints** [comment]
@BobbyBorisov nope, feel free. 

Let's nail down the terminology first. I think "Like" is a good word for what we're trying to achieve here. Looking around I found the following library which we could use? https://github.com/cybercog/laravel-likeable

**Comment by BobbyBorisov** [comment]
Hey @driesvints , I think 'Like' is better than other words like 'Favorite' and etc as well. I got free time today and i decided to implement this feature. Unfortunately i saw the **likeable** package when i was halfway through the implementation and tests(It is just one trait). I submitted the first version of it and i can do a [WIP] pull-request in order you to see it. What is left is to write comments and to style the button/thumbs up or thumbs down.

**Comment by latr88** [comment]
Thank you for looking and working into this, "Like" sounds good to me
@bobbyborisov. We really needed this feature.

**Comment by driesvints** [comment]
@BobbyBorisov yeah, just "liking" a post is fine. No need for it to go negative. Submit it and let's see if we continue from your PR or if we're going to use the package :)

**Comment by driesvints** [comment]
This is now merged and deployed.
