### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by yogasukma** [laravelio/portal#339]
Hi, i checked the previous commit https://github.com/laravelio/portal/search?q=rss&type=Commits&utf8=%E2%9C%93 and found that laravel.io has RSS feed before, but it seems now it can be accessed, not found.  
  
So, is there the RSS feed removed by purpose or missed it after redesign the site?

**Comment by driesvints** [comment]
Heya. Yeah, V1 had an RSS feed. But it got removed in the version thereafter. I'm still planning on adding one for the site although I'm not sure if it's useful for just a forum?

**Comment by yogasukmap** [comment]
I think it's useful especially for people like me (I know it's self centic
:)) who use RSS client to follow news and community at one place, get
updates and also can jump in quickly.

Do you want me to help with this RSS things?

**Comment by driesvints** [comment]
@yogasukmap You're always free to send in a PR! Perhaps we can leverage this package? https://github.com/spatie/laravel-feed

**Comment by yogasukmap** [comment]
Ok will try to play around
