### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055 'portal.threads.author_id' isn't in GROUP BY

### ISSUE THREAD

**Issue by wilburpowery** [laravelio/portal#345]
Any idea why I get this error? 
It only happens when visiting the `/forum` route.
<img width="1440" alt="screen shot 2018-01-31 at 5 04 26 pm" src="https://user-images.githubusercontent.com/15817188/35652380-f6189054-06a8-11e8-9b74-b3d0d48f6e7c.png">

**Comment by wilburpowery** [comment]
@driesvints, this is the error I mentioned in the other issue.

**Comment by driesvints** [comment]
@wilburpowery are you using the DB on Homestead? I can't seem to reproduce.

**Comment by driesvints** [comment]
I'm going to close this now but feel free to reply if you still experience this.

**Comment by michael-sbs** [comment]
![screenshot 2019-01-02 at 18 34 57](https://user-images.githubusercontent.com/39569858/50606291-21315600-0ebd-11e9-94f8-bc11f5412833.png)

I managed to resolve it temporarily by adding the following groupby attributes to the query.

However, I believe a better fix is needed and I will continue digging into it and raise a PR when I can.

**Comment by InvokerMaster** [comment]
Laravel can enable ONLY_FULL_GROUP_BY when querying using config variable.
on `config/datagase.php`
set 'strict' => false
It should work.
