### ISSUE TITLE
Add logo to mailables

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#358]
It would be cool if the Laravel.io logo was shown instead of the "Laravel.io" title on top. Perhaps also remove the gray background and just resort to white.

![screen shot 2018-03-25 at 4 46 30 pm](https://user-images.githubusercontent.com/594614/37876406-251b3a56-304c-11e8-9c71-5103f0aed6ff.png)

Logo:

![laravelio-logo-lg](https://user-images.githubusercontent.com/594614/44959066-3aaf9a80-aee9-11e8-9ebc-3690dfbfe344.png)

**Comment by joshuamabina** [comment]
Hi @driesvints,
I am interested in taking on this issue. Would appreciate any guidance.
