### ISSUE TITLE
Suggestion: Use Dependabot to keep dependencies up to date

### ISSUE THREAD

**Issue by greysteil** [laravelio/portal#379]
First of all, thanks for Laravel.io!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/portal/pulls). I'll port the `doctrine/dbal` one across to this repo now.

I built Dependabot and give it away for free to open source projects (partly for the exposure, but mainly because it feels good to give back). I'd love you to use it - hopefully it can save you a bit of time keeping on top of dependencies. It's a pretty robust product there days (over 8,000 PHP PRs merged) but if there's anything about it that you think could be better I'm always interested in feedback, too.

If you do decide to give Dependabot a go the easiest URL to add it from is https://github.com/apps/dependabot (alternatively you can go through the GitHub Marketplace, but the flow there can be a little confusing for open-source repos on an organisation account.

:octocat:

**Comment by driesvints** [comment]
Heya. I've tried it out in the past but it didn't work out. I don't mind maintaining the dependencies myself. Thanks.
