### ISSUE TITLE
Only allow alpha_dash characters for usernames

### ISSUE THREAD

**Issue by driesvints** [laravelio/portal#460]
https://laravel.com/docs/6.x/validation#rule-alpha-dash

Needs to be updated in profile settings and user registration.

**Comment by johnson-jnr** [comment]
Hi @driesvints, is this an issue I can contribute to as a first timer? If not, is there any open issue as such. Would love to contribute.
Thanks!

**Comment by driesvints** [comment]
@johnson-jnr absolutely! Welcoming prs for this :)

**Comment by johnson-jnr** [comment]
Hi @driesvints I'm still on this, stuggling to set up the environment for the project. Using the laravel documentation to set up homestead but having issues. Any guide will be appreciated but I'll still try to figure it out.

**Comment by joedixon** [comment]
Hi @johnson-jnr, we've just updated the installation instructions to use Valet rather than Homestead.

Can you try getting setup again and let us know if you still continue to have issues?

**Comment by johnson-jnr** [comment]
Hi @joedixo, thanks for updating the documentation but i'm using Windows, I think I'll be able to install using homestead now. Is there a way I can access the steps again? 
Thanks.

**Comment by driesvints** [comment]
@johnson-jnr unfortunately we've already removed all related files for Homestead so that's not possible anymore sorry.

**Comment by johnson-jnr** [comment]
alright. I found a way for valet on windows. I'll see if I can get that to work. 
Thanks.
